kind: ConfigMap
apiVersion: v1
metadata:
  name: shiro-config
  namespace: default
data:
  shiro.ini: |-
    [users]
    admin=secret, admin
    [urls]
    /api/version = anon
    /api/interpreter/setting/restart/** = authc
    /api/interpreter/** = authc, roles[admin]
    /api/configurations/** = authc, roles[admin]
    /api/credential/** = authc, roles[admin]
    /** = authc
