apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: {{ template "fluent-bit.fullname" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fluent-bit.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/v1/metrics/prometheus"
        prometheus.io/port: "8080"
{{- end }}

    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "fluent-bit.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
      - name: fluent-bit
        image: "{{ .Values.image.fluent_bit.repository }}:{{ .Values.image.fluent_bit.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
#        command: ['sh', '-c', 'sleep 10000' ]
        env:
{{- if .Values.backend.forward.tls.enabled }}
        - name: FLUENT_TLS_PASS
          valueFrom:
            secretKeyRef:
              name: fluent-tls
              key: fluent-tls-pass
        - name: FLUENT_SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: fluent-tls
              key: fluent-shared-key
{{- end }}


        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
{{ if .Values.on_minikube }}
        - name: mnt
          mountPath: /mnt
          readOnly: true
{{ end }}
{{- if .Values.backend.forward.tls.enabled }}
        - name: fluent-tls
          mountPath: /fluent-bit/ssl/
          readOnly: true
{{- end }}
        - name: position-store
          mountPath: /fluent-bit/storage
      terminationGracePeriodSeconds: 10
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- if .Values.backend.forward.tls.enabled }}
      - name: fluent-tls
        secret:
          secretName: fluent-tls
{{- end }}
      - name: config
        configMap:
          name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{- else }}{{ template "fluent-bit.fullname" . }}-config{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
{{ if .Values.on_minikube }}
      - name: mnt
        hostPath:
          path: /mnt
{{ end }}

      - name: position-store
      {{- if .Values.positionStore.persistence.enabled }}
        hostPath:
          path: /tmp
      {{- else }}
        emptyDir: {}
      {{- end -}}
