{{- if not .Values.vault.dev }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-init
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "vault.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: vault-init
        image: "{{ .Values.unsealer.image.repository }}:{{ .Values.unsealer.image.tag }}"
        command: ["vault-unsealer", "init"]
        args: ["--google-cloud-kms-key-ring",
               "vault",
               "--google-cloud-kms-crypto-key",
               "vault-unsealer",
               "--google-cloud-kms-location",
               "global",
               "--google-cloud-storage-bucket",
               "vault-ha",
               "--google-cloud-kms-project",
               "continual-air-196513"]
        env:
          - name: VAULT_ADDR
            value: http://{{ template "vault.fullname" . }}:8200
      restartPolicy: OnFailure
  backoffLimit: 4
{{- end }}
