apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: {{ template "fullname" . }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  {{ .Values.metrics.listen }}
        HTTP_Port    {{ .Values.metrics.port }}
{{- else }}
        HTTP_Server  Off
{{- end }}

    [INPUT]
        Name             {{ .Values.input.name }}
        Path             {{ .Values.input.path }}
        Parser           {{ .Values.input.parser }}
        Tag              {{ .Values.input.tag }}
        Refresh_Interval {{ .Values.input.refreshInterval }}
        Mem_Buf_Limit    {{ .Values.input.memBufLimit }}
        Skip_Long_Lines  {{ .Values.input.skipLongLines }}
{{- if .Values.input.positionStore }}
        db               {{ .Values.input.positionStore }}
{{- end }}

    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         {{ .Values.filter.kubeURL }}
        Kube_CA_File     {{ .Values.filter.kubeCAFile }}
        Kube_Token_File  {{ .Values.filter.kubeTokenFile }}
{{- if .Values.filter.mergeJSONLog }}
        Merge_JSON_Log   On
{{- end }}
{{ if eq .Values.backend.type "test" }}
    [OUTPUT]
        Name  file
        Match *
        Path /tmp/fluent-bit.log
{{ else if eq .Values.backend.type "forward" }}
    [OUTPUT]
        Name          forward
        Match         *
        Host          {{ .Values.backend.forward.host }}
        Port          {{ .Values.backend.forward.port }}
        Retry_Limit False
{{- if .Values.backend.forward.tls.enabled }}
        tls               On
        tls.verify        {{ .Values.backend.forward.tls.verify }}
        tls.ca_file       /fluent-bit/ssl/ca.crt.pem
        tls.crt_file      /fluent-bit/ssl/client.crt.pem
        tls.key_file      /fluent-bit/ssl/client.key.pem
        tls.key_passwd    ${TLS_PRIVATE_KEY_PASSPHRASE}
        Shared_Key        ${SHARED_KEY}
{{- end }}

{{ else if eq .Values.backend.type "es" }}
    [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.backend.es.host }}
        Port  {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit False
{{ else if eq .Values.backend.type "http" }}
    [OUTPUT]
        Name  http
        Match *
        Host {{ .Values.backend.http.host }}
        Port {{ .Values.backend.http.port }}
        URI {{ .Values.backend.http.uri }}
{{- if .Values.backend.http.proxy }}
        Proxy {{ .Values.backend.http.proxy }}
{{- end }}
        Format {{ .Values.backend.http.format }}
{{- end }}